baseURL: 'https://kavithaigal.github.io'
title: Kavithaigal
theme: ../../../kavithaigal.github.io
description: 'Website template for Kavithaigal'
homepage: 'https://kavithaigal.github.io'
defaultContentLanguage: 'en'
enableRobotsTXT: true
paginate: 10
hasCJKLanguage: true
copyright: "2024 Kavithaigal All rights reserved"
Author:
  name: "Suriya Ganesh"
  email: "suriyaganesh097@gmail.com"
staticDir:
  - static
ignoreFiles:
  - _example.file.md
params:
  brand: Kavithaigal
  avatarURL: /images/words.jpeg
  author: Kavithai
  authorDescription: Is a tamil word for a poem that is written over a subject
  info: We love a nice poem as much as any person â¤ï¸â€ðŸ”¥
  favicon: /images/words.jpeg
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="currentColor" stroke="#000000" height="25" width="25" version="1.1" id="Layer_1" viewBox="0 0 310 310" xml:space="preserve">
        <g id="XMLID_822_">
        <path id="XMLID_823_" d="M297.917,64.645c-11.19-13.302-31.85-18.728-71.306-18.728H83.386c-40.359,0-61.369,5.776-72.517,19.938   C0,79.663,0,100.008,0,128.166v53.669c0,54.551,12.896,82.248,83.386,82.248h143.226c34.216,0,53.176-4.788,65.442-16.527   C304.633,235.518,310,215.863,310,181.835v-53.669C310,98.471,309.159,78.006,297.917,64.645z M199.021,162.41l-65.038,33.991   c-1.454,0.76-3.044,1.137-4.632,1.137c-1.798,0-3.592-0.484-5.181-1.446c-2.992-1.813-4.819-5.056-4.819-8.554v-67.764   c0-3.492,1.822-6.732,4.808-8.546c2.987-1.814,6.702-1.938,9.801-0.328l65.038,33.772c3.309,1.718,5.387,5.134,5.392,8.861   C204.394,157.263,202.325,160.684,199.021,162.41z"/>
        </g>
        </svg>
        

      url: 'https://github.com/kavithaigal'
#    - name: Twitter
#      pre: >-
#        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
#        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
#        stroke-linecap="round" stroke-linejoin="round" class="feather
#        feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0
#        0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20
#        0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>
#      url: 'https://twitter.com/*'
languages:
  en:
    languageName: English
    menu:
      main:
        - name: Blog
          url: /blog
          weight: 1
        - name: People
          url: /people
          weight: 3
taxonomies:
  series: series
  tag: tags
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false